"""Step 04 — Draft.

Draft a personalised email + LinkedIn message from the trigger, contact and assets.

Owner: Loïc
Inputs:  DraftRequest
Outputs: OutreachDraft

The full prompt system + standalone demo live outside the repo for now
(../drafting/). This stub returns a mock draft so the pipeline runs end to end;
wire in the real LLM call here.
"""

from __future__ import annotations

from ..schemas import DraftRequest, Email, OutreachDraft


def draft(req: DraftRequest) -> OutreachDraft:
    """Produce an email + LinkedIn message for the request.

    TODO: build the prompt from ``req`` and call the LLM (see ../drafting/).
    """
    name = req.contact.full_name.split()[0]
    return OutreachDraft(
        email=Email(
            subject="<trigger-based subject>",
            body=f"Hi {name},\n\n<draft generated by the LLM>\n\n"
            f"Best,\n{req.assets.sender_name} — {req.assets.sender_title}",
            cta="<single call to action>",
        ),
        linkedin_message=f"Hi {name}, <short LinkedIn draft generated by the LLM>",
        rationale="<why this angle> (stub)",
        confidence="low",
        flags=["stub_output"],
    )
